# Generated by Django 4.2.3 on 2026-03-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='main_photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
