# Generated by Django 4.2.3 on 2026-03-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=400, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='main_photo',
            field=models.ImageField(upload_to='media', verbose_name='Головне фото'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=55, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
